[package]
name         = "ibc-relayer-types"
version      = "0.22.0"
edition      = "2021"
license      = "Apache-2.0"
readme       = "README.md"
keywords     = ["blockchain", "consensus", "cosmos", "ibc", "tendermint"]
repository   = "https://github.com/informalsystems/hermes"
authors      = ["Informal Systems <hello@informal.systems>"]
rust-version = "1.65"
description  = """
    Implementation of the Inter-Blockchain Communication Protocol (IBC).
    This crate comprises the main data structures and on-chain logic.
"""

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std"]
std = ["flex-error/std", "flex-error/eyre_tracer", "ibc-proto/std", "clock"]
clock = ["tendermint/clock", "time/std"]

# This feature grants access to development-time mocking libraries, such as `MockContext` or `MockHeader`.
# Depends on the `testgen` suite for generating Tendermint light blocks.
mocks = ["tendermint-testgen", "clock", "std"]

[dependencies]
# Proto definitions for all IBC-related interfaces, e.g., connections or channels.
ibc-proto = { git = "https://github.com/heliaxdev/ibc-proto-rs.git", rev = "bb16e17a4d9260d5f20516a8eda43fa52377fad2", default-features = false }
ics23 = { version = "=0.9.0", default-features = false, features = ["host-functions"] }
time = { version = ">=0.3.0, <0.3.18", default-features = false }
serde_derive = { version = "1.0.104", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1", default-features = false }
erased-serde = { version = "0.3", default-features = false, features = ["alloc"] }
prost = { version = "0.11", default-features = false }
bytes = { version = "1.3.0", default-features = false }
safe-regex = { version = "0.2.5", default-features = false }
subtle-encoding = { version = "0.5", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "into", "display"] }
uint = { version = "0.9", default-features = false }
itertools = { version = "0.10.3", default-features = false, features = ["use_alloc"] }
primitive-types = { version = "0.12.1", default-features = false, features = ["serde_no_std"] }
dyn-clone = "1.0.8"
num-rational = "0.4.1"

[dependencies.tendermint]
git = "https://github.com/heliaxdev/tendermint-rs.git"
rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7"
default-features = false

[dependencies.tendermint-proto]
git = "https://github.com/heliaxdev/tendermint-rs.git"
rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7"
default-features = false

# Temporary, until this change makes it into a tendermint-rs release:
# https://github.com/informalsystems/tendermint-rs/pull/1204
[dependencies.tendermint-rpc]
git = "https://github.com/heliaxdev/tendermint-rs.git"
rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7"
default-features = false

[dependencies.tendermint-light-client-verifier]
git = "https://github.com/heliaxdev/tendermint-rs.git"
rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7"
default-features = false

[dependencies.tendermint-testgen]
git = "https://github.com/heliaxdev/tendermint-rs.git"
rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7"
optional = true
default-features = false

[dev-dependencies]
env_logger = "0.10.0"
tracing = { version = "0.1.36", default-features = false }
tracing-subscriber = { version = "0.3.14", features = ["fmt", "env-filter", "json"]}
test-log = { version = "0.2.10", features = ["trace"] }
modelator = "0.4.2"
tendermint-rpc = { features = ["http-client", "websocket-client"], git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7" }
tendermint-testgen = { git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "b7d1e5afc6f2ccb3fd1545c2174bab1cc48d7fa7" } # Needed for generating (synthetic) light blocks.
