# Build Hermes Docker image, push to Docker Hub and GHCR.io.

name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.*

env:
  REGISTRY_IMAGE: heliaxdev/hermes

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - id: linux/amd64
            name: amd64
          - id: linux/arm64
            name: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/hermes
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ci/release/hermes.Dockerfile
          platforms: ${{ matrix.platform.id }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
