name: Guide Template Checker
on:
  pull_request:
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/relayer-cli/**
      - scripts/**
      - tools/check-guide/**
      - guide/src/templates/**

  push:
    branches: master
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/relayer-cli/**
      - scripts/**
      - tools/check-guide/**
      - guide/src/templates/**

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  template-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mold: [2.1.0]
    env:
      RUSTFLAGS: '-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold'
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install mold linker
        run: |
          wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold }}/mold-${{ matrix.mold }}-x86_64-linux.tar.gz | tar -xz
          mv mold-${{ matrix.mold }}-x86_64-linux/bin/mold /usr/local/bin
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
      - name: Check templates
        run: bash scripts/auto_gen_templates.sh --mode "check"
      - uses: actions-rs/cargo@v1
        name: Update lockfile
        with:
          command: generate-lockfile
          args: --manifest-path tools/check-guide/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: Check guide
        with:
          command: run
          args: --manifest-path tools/check-guide/Cargo.toml
