name: Namada E2E test
on:
  pull_request:
    paths:
      - .github/workflows/integration.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - e2e/**
      - crates/**
      - tools/**
  push:
    branches: '*-namada'
    paths:
      - .github/workflows/integration.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - e2e/**
      - crates/**
      - tools/**

jobs:
  namada-e2e-test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        namada: [0.23.0]
        comet_bft: [0.37.2]
        mold: [2.1.0]

    env:
      RUSTFLAGS: '-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold'

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
      - name: Install mold linker
        run: |
          wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold }}/mold-${{ matrix.mold }}-x86_64-linux.tar.gz | tar -xz
          mv mold-${{ matrix.mold }}-x86_64-linux/bin/mold /usr/local/bin
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin hermes
      - name: Download CometBFT
        run: |
          curl -o cometbft.tar.gz -LO https://github.com/cometbft/cometbft/releases/download/v${{ matrix.comet_bft }}/cometbft_${{ matrix.comet_bft }}_linux_amd64.tar.gz
          tar -xvzf cometbft.tar.gz
          mv cometbft /usr/local/bin
      - name: Install wasm-opt
        run: |
          curl -o binaryen.tar.gz -LO https://github.com/WebAssembly/binaryen/releases/download/version_114/binaryen-version_114-x86_64-linux.tar.gz
          tar -xvzf binaryen.tar.gz
          mv binaryen-version_114/bin/wasm-opt /usr/local/bin
      - name: Clone Namada
        uses: actions/checkout@v3
        with:
          repository: anoma/namada
          ref: v${{ matrix.namada }}
          path: namada
      - name: Build Namada
        run: |
          cd namada
          make build-release && make build-wasm-scripts
      - name: Run test
        run: |
          pip3 install toml
          e2e/namada-e2e-test namada
      - name: Upload e2e logs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ibc_e2e_log
          path: e2e/ibc_e2e.log
          retention-days: 5
