name: Publish (dry-run)

on:
  push:
    branches:
      - 'release/*'

jobs:
  publish:
    name: Publish (dry-run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protoc
        uses: heliaxdev/setup-protoc@v2
        with:
          version: "25.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: katyo/publish-crates@v2
        with:
          dry-run: true

